### ISSUE TITLE
samsung XE303C12

### ISSUE THREAD

**Issue by F0rth** [altreact/archbk#1]
Hi,

On the classic (old) samsung xe303 (first one) your script work without hiccup.
Another source of tips http://elatov.github.io/2014/02/install-arch-linux-samsung-chromebook/
got pulseaudio working with thoses instructions. 
How to reduce the 30 seconds boot annoyance: https://www.reddit.com/r/Crouton/comments/2szn59/how_to_shorten_os_verfication_warning_screen_on/
And a xorg conf file for xf86-video-armsoc:
https://build.opensuse.org/package/view_file/devel:ARM:Factory:Contrib:Chromebook/xf86-video-armsoc/exynos.conf?expand=1

**Comment by altreact** [comment]
awesome info Forth!

Thanks for the confirmation! (On the classic (old) samsung xe303 (first one) your script work without hiccup.)
