### ISSUE TITLE
very strange NetworkManager bug

### ISSUE THREAD

**Issue by F0rth** [altreact/archbk#2]
For the records, I encountered a very strange bug with nm. Netcl worked ok but I'm more familiar with nm.
I disabled netctl, systemd-networked bs and dhcpcd. I tried nm with dhcp=dhclient or dhcpcd or internal.
They got their ip address right (dhcp) but the routing table was ok 1 second and then blanked to its pristine virginal state (no routing entry).
What is working on my chromebook (for now):
- no NetworkManager.conf, nm use dhclient since its installed;
- enable dhcpcd service at boot.

**Comment by altreact** [comment]
Thank you for your input F0rth. 

I personally use netctl, which is included in, and also the standard for Arch Linux ARM. 

For more information / support for network manager and / or all things Arch Linux / Arch Linux Arm, visit:

https://wiki.archlinux.org/index.php/NetworkManager

https://wiki.archlinux.org/index.php

https://archlinuxarm.org/wiki

https://archlinuxarm.org/forum/

Thanks again for your input.
