### ISSUE TITLE
asus c201

### ISSUE THREAD

**Issue by masnatacion** [altreact/archbk#4]
hi

after run 

`sh helper.sh`

i got this message when i try to install the ARCH from USB to Chromebook:

`primary GPT header is being ignored`

and when finally finish and reboot got a Invalid recovery media.

can u help me?

thank u

**Comment by altreact** [comment]
A similar issue has come up with a similar device.

You may be able to install to internal flash by following the instructions [here:](https://github.com/altreact/archbk/issues/3) 

Unfortunately, This seems to be an issue that's exclusive to the asus c201, to the Asus Flip C100PA, and possibly to any other cbromebook with the same chipset as the two that have been mentioned. 

I don't have a the free time to troubleshoot the issue with these asus chrombooks and to patch the script at the moment. Yet, if someone verifies the process that worked for them, I'll do my best to chef up a patch and to update the 

> [script.``](url)

**Comment by kapouer** [comment]
Hello !
Even on a sane installation, "invalid recovery media" happens often on reboot.
On Debian doing a simple reboot does that (installed using https://github.com/Maccraft123/Cadmium)
