### ISSUE TITLE
Does The Script Work For USB's???

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [altreact/archbk#8]
I found in most OS's for arm chromebook that they don't work sometimes for USB's...
these are the OS's that I've tried with USB's

OpenSUSE: YES
Fedora 19 (Very Old... Out of date and does not support packages anymore): NOPE
KaliLinux: DEPENDS
Bodhi Linux: From What I Heard No
ArchLinuxArmScript/Archbk: ???

**Comment by altreact** [comment]
Yes. The script installs ArchLinuxArm on USB flash drives for use with ARM
ChromeBooks. For details about the script and installation, read the readme
file at https://GitHub.com/altreact/archbk

**Comment by EnderNightLord-ChromeBook** [comment]
Cool thx bro

**Comment by altreact** [comment]
Yw. Let me know how it works out for you.
