### ISSUE TITLE
alarm login?

### ISSUE THREAD

**Issue by Topquants** [altreact/archbk#9]
Script seems to have worked up until login.

I'm seeing "alarm login:"

root/root doesn't work.
alarm/alarm doesn't work.

I'm on a chromebook plus.  

Is there another user/pass or workaround to use?

**Comment by altreact** [comment]
I'm sorry that you are having issues with login. I reinstalled a week ago, and username: root, password: root worked. again, i just wrote the install script, and i have no involvement with the inner workings of arch linux arm. For support for the actual operating system, see the arch linux arm community.
